#!/usr/bin/env bash

BASE_LOCATION=/Users/lennart.kroneman
LOG_LOCATION=$BASE_LOCATION/bin/logs/every-minute.log

log_start() {
    mkdir -p $BASE_LOCATION/bin/logs
    echo "Every Minute Ran on $(date)" >> $LOG_LOCATION
}

send_email() {
    local result="$(/Users/lennart.kroneman/.asdf/shims/node $BASE_LOCATION/bin/mailer/sendMail.js)"
    echo $result >> $LOG_LOCATION
}

main() {
    log_start
    # send_email
    echo "Finished run successfully" >> $LOG_LOCATION
}

main "$@";