const { CI } = process.env;
const isCI = CI === 'true';

const macCowsayAvatars = [
    // 'beavis.zen',
    'blowfish',
    // 'bong',
    // 'bud-frogs',
    // 'bunny',
    'cheese',
    'cower',
    // 'daemon',
    'default',
    'dragon',
    'dragon-and-cow',
    'elephant',
    'elephant-in-snake',
    // 'eyes',
    // 'flaming-sheep',
    // 'ghostbusters',
    'hellokitty',
    // 'kiss',
    // 'kitty',
    'koala',
    'kosh',
    // 'luke-koala',
    'meow',
    'milk',
    'moofasa',
    'moose',
    // 'mutilated',
    // 'ren',
    // 'satanic',
    'sheep',
    // 'skeleton',
    'small',
    'stegosaurus',
    'stimpy',
    'supermilker',
    // 'surgery',
    // 'three-eyes',
    // 'turkey',
    'turtle',
    'tux',
    // 'udder',
    'vader',
    'vader-koala',
    // 'www'
];

const linuxCowsayAvatars = [
    // 'apt',
    'calvin',
    // 'cower',
    'dragon-and-cow',
    // 'elephant-in-snake',
    // 'flaming-sheep',
    'gnu',
    // 'kiss',
    'luke-koala',
    'moofasa',
    'pony',
    // 'skeleton',
    // 'stimpy',
    'turkey',
    // 'unipony-smaller',
    'vader',
    'bud-frogs',
    'cheese',
    // 'daemon',
    // 'dragon',
    'elephant',
    'fox',
    'hellokitty',
    'koala',
    'mech-and-cow',
    'moose',
    // 'ren',
    'snowman',
    'suse',
    'turtle',
    // 'unipony',
    // 'www',
    // 'bunny',
    // 'cock',
    'default',
    // 'duck',
    'eyes',
    'ghostbusters',
    // 'kangaroo',
    // 'kosh',
    'milk',
    // 'pony-smaller',
    'sheep',
    'stegosaurus',
    // 'three-eyes',
    'tux',
    'vader-koala',
];

module.exports = isCI ? linuxCowsayAvatars : macCowsayAvatars;
