const cowsayAvatars = [
    // 'beavis.zen',
    'blowfish',
    // 'bong',
    // 'bud-frogs',
    // 'bunny',
    'cheese',
    'cower',
    // 'daemon',
    'default',
    'dragon',
    'dragon-and-cow',
    'elephant',
    'elephant-in-snake',
    // 'eyes',
    // 'flaming-sheep',
    // 'ghostbusters',
    'hellokitty',
    // 'kiss',
    // 'kitty',
    'koala',
    'kosh',
    // 'luke-koala',
    'meow',
    'milk',
    'moofasa',
    'moose',
    // 'mutilated',
    // 'ren',
    // 'satanic',
    'sheep',
    // 'skeleton',
    'small',
    'stegosaurus',
    'stimpy',
    'supermilker',
    // 'surgery',
    // 'three-eyes',
    // 'turkey',
    'turtle',
    'tux',
    // 'udder',
    'vader',
    'vader-koala',
    // 'www'
];

module.exports = cowsayAvatars;